version = 0.1
[default.deploy.parameters]
stack_name = "trivia-app"
resolve_s3 = true
s3_prefix = "trivia-app"
region = "us-east-1"
profile = "oren_cli_linux"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
